# -*- coding: utf-8 -*-
"""Finalizado - Simulação de Máquina de Indução Trifásica - Experimentos de Partida

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16YGLQrljf2TpufPkQG876Wa80I0LGRjf
"""

# @title Bibliotecas
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint
from IPython.display import display

"""---

# O Colab aqui apresentado tem o objetivo de simular situações específicas no funcionamento de uma máquina de indução trifásica.

# 1. Partida Direta (DOL - Direct On Line)

**Objetivo:** Analisar a corrente e o torque de partida diretos.

**Configuração:**

- **Modo de Operação:** Motor  
- **Tensão RMS de entrada** ($V_l$): 220.0 V  
- **Frequência** ($f$): 60.0 Hz  
- **Torque mecânico inicial** ($T_{l\_initial}$): 0.0 Nm  
- **Torque mecânico final** ($T_{l\_final}$): 80.0 Nm (valor nominal sugerido)  
- **Tempo de aplicação do torque mecânico** ($t_{carga}$): 0.1 s (aplicar torque logo no início)  
- **Referência para a transformada de Park:** Síncrona ($\omega_e$)

**Análise Esperada:** Observar picos elevados de corrente e torque na partida.

## 1.1. Alterações a serem feitas:
Na partida direta, a máquina começa com uma rotação nula e uma alimentação nominal entre os terminais.
$$ wr_{initial} = 0 RPM$$
$$V_l = 220 V$$
"""

# @title Parâmetros de simulação para partida direta
print('Simulação de máquina de indução gaiola de esquilo trifásica')
print('Partida direta (DOL - Direct On Line)')

## Simulation Parameters (using @param for interactive input)
print('\nParâmetros de simulação:')
tmax = 2  # @param {type:"slider", min:0.1, max:10.0, step:0.1, default:2.0}
print(f"tmax (Tempo de simulação) = {tmax} s")
h = 0.001  # @param {type:"slider", min:0.00001, max:0.001, step:0.00001, default:0.0001}
t_carga = 0.1  # @param {type:"slider", min:0.1, max:5.0, step:0.1, default:1.0}
print(f"t_2 (Tempo de aplicação do torque mecânico) = {t_carga} s")

## Motor Operation Mode (using @param for interactive input)
print('\nModo de operação da máquina de indução:')
mop_choice = "Motor"  # @param ["Motor", "Gerador conectado ao barramento infinito"]
mop = 1 if mop_choice == "Motor" else 2

## Three-Phase Induction Machine Simulation Parameters (using @param for interactive input)
print('\nParâmetros de dados da máquina de indução trifásica:')
Vl = 220  # @param {type:"slider", min:10.0, max:500.0, step:10.0, default:220.0}
print(f"Vl (Tensão RMS de linha) = {Vl} V")
f = 60.0  # @param {type:"slider", min:10.0, max:120.0, step:1.0, default:60.0}
print(f"f (Frequência) = {f} Hz")
Rs = 0.435  # @param {type:"slider", min:0.1, max:5.0, step:0.01, default:0.435}
print(f"Rs (Resistência do estator) = {Rs} Ω")
Rr = 0.816  # @param {type:"slider", min:0.1, max:5.0, step:0.01, default:0.816}
print(f"Rr (Resistência do rotor) = {Rr} Ω")
Xm = 26.13  # @param {type:"slider", min:1.0, max:100.0, step:0.1, default:26.13}
print(f"Xm (Reatância de magnetização) = {Xm} Ω")
Xls = 0.754  # @param {type:"slider", min:0.1, max:5.0, step:0.01, default:0.754}
print(f"Xls (Reatância de dispersão do estator) = {Xls} Ω")
Xlr = 0.754  # @param {type:"slider", min:0.1, max:5.0, step:0.01, default:0.754}
print(f"Xlr (Reatância de dispersão do rotor) = {Xlr} Ω")
p = 4  # @param {type:"slider", min:2, max:8, step:2, default:4}
print(f"p (Número de polos) = {p}")
J = 0.089  # @param {type:"slider", min:0.01, max:1.0, step:0.001, default:0.089}
print(f"J (Inércia do rotor) = {J} kg·m²")
Tl_initial = 0.0  # @param {type:"slider", min:0.0, max:200.0, step:1.0, default:0.0}
print(f"Tl_initial (Torque inicial) = {Tl_initial} Nm")
Tl_final = 80  # @param {type:"slider", min:0.0, max:200.0, step:1.0, default:80.0}
print(f"Tl_final (Torque final) = {Tl_final} Nm")
# Torque final nulo pois consideraremos a máquina apenas em vazio.
B = 0.0  # @param {type:"slider", min:0.0, max:1.0, step:0.001, default:0.0}
print(f"B (Campo magnético inicial) = {B} Nm·s/rad")


## Park Transform Reference Option (using @param for interactive input)
print('\nEscolha a velocidade angular de referência para a transformada de Park:')
ref_choice = "referência síncrona (we)"  # @param ["referência síncrona (we)", "referência rotórica (wr)", "referência estacionária (0)"]
if ref_choice == "referência síncrona (we)":
    ref = 1
elif ref_choice == "referência rotórica (wr)":
    ref = 2
else:
    ref = 3

if mop == 1:
    print("\nModo de operação: motor")
    Tl = Tl_initial
    Tl_2 = Tl_final
else:
    print("\nModo de operação: gerador conectado ao barramento infinito")
    Tl = -Tl_initial
    Tl_2 = -Tl_final

if ref == 1:
    print('Referência: síncrona (we)')
elif ref == 2:
    print('Referência: rotórica (wr)')
else:
    print('Referência: estacionária (0)')


# Definição das variáveis para iteração
PSIqs_initial = 0
PSIds_initial = 0
PSIqr_initial = 0
PSIdr_initial = 0
wr_initial = 0 # @param {"type":"slider","min":0,"max":3600,"step":50}
# Na partida, a rotação do eixo é nula.
initial_states = [PSIqs_initial, PSIds_initial, PSIqr_initial, PSIdr_initial, wr_initial]

# @title Simulador

# Cálculo de parâmetros
Xml = 1 / ((1 / Xm) + (1 / Xls) + (1 / Xlr))
wb = 2 * np.pi * f  # Base angular velocity
Vqr_squirrel_cage = 0
Vdr_squirrel_cage = 0 # Squirrel cage rotor

## State-Space Representation and ODEs
def induction_motor_equations(states, t, Vqs_t, Vds_t, current_Tl, w_ref_val):
    PSIqs, PSIds, PSIqr, PSIdr, wr = states

    # Dependent variables calculation
    PSImq = Xml * (PSIqs / Xls + PSIqr / Xlr)
    PSImd = Xml * (PSIds / Xls + PSIdr / Xlr)
    ids_val = (1 / Xls) * (PSIds - PSImd)
    iqs_val = (1 / Xls) * (PSIqs - PSImq)

    # Differential equations
    dPSIqs_dt = wb * (Vqs_t - (w_ref_val / wb) * PSIds + (Rs / Xls) * (PSImq - PSIqs))
    dPSIds_dt = wb * (Vds_t + (w_ref_val / wb) * PSIqs + (Rs / Xls) * (PSImd - PSIds))
    dPSIqr_dt = wb * (Vqr_squirrel_cage - ((w_ref_val - wr) / wb) * PSIdr + (Rr / Xlr) * (PSImq - PSIqr))
    dPSIdr_dt = wb * (Vdr_squirrel_cage + ((w_ref_val - wr) / wb) * PSIqr + (Rr / Xlr) * (PSImd - PSIdr))

    # Electromagnetic torque
    Tem_val = (3 / 2) * (p / 2) * (1 / wb) * (PSIds * iqs_val - PSIqs * ids_val)
    dwr_dt = (p / (2 * J)) * (Tem_val - current_Tl) - (B / J) * wr

    return [dPSIqs_dt, dPSIds_dt, dPSIqr_dt, dPSIdr_dt, dwr_dt]

## Simulation Loop (using odeint for integration)
t_values = np.arange(0, tmax, h)

# Store results
wr_results = []
Te_results = []
n_results = []
ids_results = []
iqs_results = []
idr_results = []
iqr_results = []
ias_results = []
ibs_results = []
ics_results = []
iar_results = []
ibr_results = []
icr_results = []
Va_results = []
Vb_results = []
Vc_results = []
Vds_results = []
Vqs_results = []

# To store the last `wr` value for `w_ref_val` if `ref == 2`
last_wr = wr_initial

for i, t_val in enumerate(t_values):
    # Determine mechanical torque
    if t_val >= t_carga:
        current_Tl = Tl_2
    else:
        current_Tl = Tl

    # Stator electrical components
    we_val = 2 * np.pi * f
    tetae = we_val * t_val

    # Define arbitrary reference for the transform based on input choice
    if ref == 1:
        w_ref_val = we_val
    elif ref == 2:
        w_ref_val = last_wr  # Use the last calculated wr
    else:
        w_ref_val = 0

    # Input voltage (infinite bus)
    Va_val = np.sqrt(2) * Vl * np.sin(tetae)
    Vb_val = np.sqrt(2) * Vl * np.sin(tetae - ((2 * np.pi) / 3))
    Vc_val = np.sqrt(2) * Vl * np.sin(tetae + ((2 * np.pi) / 3))

    Vaf_val = np.sqrt(3 / 2) * (Va_val + (-1 / 2) * Vb_val + (-1 / 2) * Vc_val)
    Vbt_val = np.sqrt(3 / 2) * (0 * Va_val + (np.sqrt(3) / 2) * Vb_val + (-np.sqrt(3) / 2) * Vc_val)

    Vds_val = np.cos(tetae) * Vaf_val + np.sin(tetae) * Vbt_val
    Vqs_val = -np.sin(tetae) * Vaf_val + np.cos(tetae) * Vbt_val

    # Integrate one step using odeint
    sol = odeint(induction_motor_equations, initial_states, [t_val, t_val + h], args=(Vqs_val, Vds_val, current_Tl, w_ref_val))
    PSIqs, PSIds, PSIqr, PSIdr, wr = sol[1] # Take the results at t_val + h
    initial_states = [PSIqs, PSIds, PSIqr, PSIdr, wr] # Update initial states for next iteration
    last_wr = wr # Update last_wr for next iteration if ref == 2

    # Store mechanical angular velocity
    wr_results.append(wr)

    # Calculate and store speed in RPM
    n = (120 / p) * (wr / (2 * np.pi))
    n_results.append(n)

    # Calculate currents and store
    PSImd = Xml * (PSIds / Xls + PSIdr / Xlr)
    PSImq = Xml * (PSIqs / Xls + PSIqr / Xlr)

    ids = (1 / Xls) * (PSIds - PSImd)
    iqs = (1 / Xls) * (PSIqs - PSImq)
    idr = (1 / Xlr) * (PSIdr - PSImd)
    iqr = (1 / Xlr) * (PSIqr - PSImq)

    ids_results.append(ids)
    iqs_results.append(iqs)
    idr_results.append(idr)
    iqr_results.append(iqr)

    # Calculate and store electromagnetic torque
    Te = (3 / 2) * (p / 2) * (1 / wb) * (PSIds * iqs - PSIqs * ids)
    Te_results.append(Te)

    # Stator and Rotor currents (alpha-beta and abc)
    tetar = wr * t_val # Using t_val for tetar calculation here, consistent with Scilab code

    iafs = np.cos(tetae) * ids - np.sin(tetae) * iqs
    ibts = np.sin(tetae) * ids + np.cos(tetae) * iqs

    iafr = np.cos(tetar) * idr - np.sin(tetar) * iqr
    ibtr = np.sin(tetar) * idr + np.cos(tetar) * iqr # Corrected to tetar, assuming original was a typo

    ias = np.sqrt(3/2) * (1 * iafs + 0 * ibts)
    ibs = np.sqrt(3/2) * ((-1/2) * iafs + (np.sqrt(3)/2) * ibts)
    ics = np.sqrt(3/2) * ((-1/2) * iafs + (-np.sqrt(3)/2) * ibts)

    iar = np.sqrt(3/2) * (1 * iafr + 0 * ibtr)
    ibr = np.sqrt(3/2) * ((-1/2) * iafr + (np.sqrt(3)/2) * ibtr)
    icr = np.sqrt(3/2) * ((-1/2) * iafr + (-np.sqrt(3)/2) * ibtr)

    ias_results.append(ias)
    ibs_results.append(ibs)
    ics_results.append(ics)
    iar_results.append(iar)
    ibr_results.append(ibr)
    icr_results.append(icr)

    Va_results.append(Va_val)
    Vb_results.append(Vb_val)
    Vc_results.append(Vc_val)
    Vds_results.append(Vds_val)
    Vqs_results.append(Vqs_val)


# Convert lists to numpy arrays for easier plotting
wr_results = np.array(wr_results)
Te_results = np.array(Te_results)
n_results = np.array(n_results)
ids_results = np.array(ids_results)
iqs_results = np.array(iqs_results)
idr_results = np.array(idr_results)
iqr_results = np.array(iqr_results)
ias_results = np.array(ias_results)
ibs_results = np.array(ibs_results)
ics_results = np.array(ics_results)
iar_results = np.array(iar_results)
ibr_results = np.array(ibr_results)
icr_results = np.array(icr_results)
Va_results = np.array(Va_results)
Vb_results = np.array(Vb_results)
Vc_results = np.array(Vc_results)
Vds_results = np.array(Vds_results)
Vqs_results = np.array(Vqs_results)


## Steady-State Values
#print("\nValores (finais) em regime permanente das variáveis:")
#print("s f_r ids iqs n")
# Assuming the last values are steady-state
s_ss = (wb - wr_results[-1]) / wb
fr_ss = wr_results[-1] / (2 * np.pi)
ids_ss = ids_results[-1]
iqs_ss = iqs_results[-1]
n_ss = n_results[-1]
#print(f"{s_ss:.4f} {fr_ss:.4f} {ids_ss:.4f} {iqs_ss:.4f} {n_ss:.4f}")

## Plotting
# Torque
plt.figure(figsize=(10, 4))
plt.subplot(2, 1, 1)
plt.plot(t_values, Te_results, label='$T_e$')
plt.title('$T_e$', fontsize=14)
plt.xlabel('tempo (segundos)', fontsize=12)
plt.ylabel('Torque (Nm)', fontsize=12)
plt.legend(loc='center left', bbox_to_anchor=(1.0, 0.5))  # legenda fora
plt.grid(True)

# Velocidade
plt.figure(figsize=(10, 4))
plt.subplot(2, 1, 2)
plt.plot(t_values, n_results, label='n (RPM)')
plt.title('n (RPM)', fontsize=14)
plt.xlabel('tempo (segundos)', fontsize=12)
plt.ylabel('Velocidade (RPM)', fontsize=12)
plt.legend(loc='center left', bbox_to_anchor=(1.0, 0.5))  # legenda fora
plt.grid(True)
plt.show()

# Stator Voltages
plt.figure(figsize=(10, 4))
plt.subplot(2, 1, 1)
plt.plot(t_values, Va_results, label='$V_a$')
plt.plot(t_values, Vb_results, label='$V_b$')
plt.plot(t_values, Vc_results, label='$V_c$')
plt.title('$V_a$ x $V_b$ x $V_c$', fontsize=14)
plt.xlabel('tempo (segundos)', fontsize=12)
plt.ylabel('Tensão (V)', fontsize=12)
plt.legend(loc='center left', bbox_to_anchor=(1.0, 0.5))
plt.grid(True)

# Stator Currents
plt.figure(figsize=(10, 4))
plt.subplot(2, 1, 2)
plt.plot(t_values, ias_results, label='$i_{as}$')
plt.plot(t_values, ibs_results, label='$i_{bs}$')
plt.plot(t_values, ics_results, label='$i_{cs}$')
plt.title('$I_{as}$ x $I_{bs}$ x $I_{cs}$', fontsize=14)
plt.xlabel('tempo (segundos)', fontsize=12)
plt.ylabel('Corrente (A)', fontsize=12)
plt.legend(loc='center left', bbox_to_anchor=(1.0, 0.5))
plt.grid(True)
plt.tight_layout()
plt.show()

# Rotor Currents
plt.figure(figsize=(10, 4))
plt.subplot(2, 1, 1)
plt.plot(t_values, iar_results, label='$i_{ar}$')
plt.plot(t_values, ibr_results, label='$i_{br}$')
plt.plot(t_values, icr_results, label='$i_{cr}$')
plt.title('$I_{ar}$ x $I_{br}$ x $I_{cr}$', fontsize=14)
plt.xlabel('tempo (segundos)', fontsize=12)
plt.ylabel('Corrente (A)', fontsize=12)
plt.legend(loc='center left', bbox_to_anchor=(1.0, 0.5))
plt.grid(True)
plt.tight_layout()
plt.show()

"""## Resultados:
Para a partida direta, percebemos uma alta corrente, se comparadas com o valor final, para o Rotor e para o Estator. Além disso, há um elevado torque de partida, mesmo que ainda não haja carga no eixo.
"""

# Obter os valores máximos:
print('Valores máximos para partida Direta - Direct on Line')
valores_max_DOL = {
  'Corrente máxima na fase A do Estator (A)': max(ias_results),
  'Corrente máxima na fase B do Estator (A)': max(ibs_results),
  'Corrente máxima na fase C do Estator (A)': max(ics_results),
    'Corrente máxima na fase A do Rotor (A)': max(iar_results),
    'Corrente máxima na fase B do Rotor (A)': max(ibr_results),
    'Corrente máxima na fase C do Rotor (A)': max(icr_results),
  'Torque máximo desenvolvido no eixo (N.m)': max(Te_results),
}

# Resultados máximos:
for item, valor in valores_max_DOL.items():
    print(f'{item}: {valor:.3f}')

"""## 2. Partida Y−Δ (Estrela-Triângulo)

**Objetivo:** Demonstrar a redução da corrente de partida e do torque de partida em comparação com a partida direta.

**Considerações:**  
No modelo $0dq$ simplificado, a partida Y−Δ é simulada reduzindo a tensão de entrada durante o período inicial de partida (equivalente a $\frac{1}{\sqrt{3}}$ da tensão nominal).

**Configuração:**

- **Modo de Operação:** Motor  
- **Tensão RMS de entrada** ($V_L$): Iniciar com aproximadamente 127.0 V ($\frac{220}{\sqrt{3}}$) por um tempo (ex: 0.5 s), depois alterar para 220.0 V  
- **Frequência** ($f$): 60.0 Hz  
- **Torque mecânico inicial** ($T_{l\_initial}$): 0.0 Nm  
- **Torque mecânico final** ($T_{l\_final}$): 80.0 Nm  
- **Tempo de aplicação do torque mecânico** ($t_{carga}$): 0.1 s  
- **Referência para a transformada de Park:** Síncrona ($\omega_e$)

**Análise Esperada:**  
Comparar as curvas de corrente e torque com a partida direta, observando a redução dos picos.

## 2.1 Alterações a serem feitas:
O Valor inicial da tensão nos parâmetros deve ser de $\frac{220}{\sqrt{3}}$ V. Após t_2 segundos, o valor deve ser o nominal que é de $220$ V.
"""

# @title Parâmetros de simulação para partida Y−Δ (Estrela-Triângulo)
print('Simulação de máquina de indução gaiola de esquilo trifásica')
print('Partida direta (DOL - Direct On Line)')

## Simulation Parameters (using @param for interactive input)
print('\nParâmetros de simulação:')
tmax = 2  # @param {type:"slider", min:0.1, max:10.0, step:0.1, default:2.0}
print(f"tmax (Tempo de simulação) = {tmax} s")
h = 0.001  # @param {type:"slider", min:0.00001, max:0.001, step:0.00001, default:0.0001}
t_2 = 0.5  # @param {type:"slider", min:0.1, max:5.0, step:0.1, default:1.0}
t_carga = 0.1 # s (Momento em que a carga é aplicada)
print(f"t_carga (Tempo de aplicação da carga) = {t_carga} s")
print(f"t_2 (Tempo de troca para Delta) = {t_2} s")

## Motor Operation Mode (using @param for interactive input)
print('\nModo de operação da máquina de indução:')
mop_choice = "Motor"  # @param ["Motor", "Gerador conectado ao barramento infinito"]
mop = 1 if mop_choice == "Motor" else 2

## Three-Phase Induction Machine Simulation Parameters (using @param for interactive input)
print('\nParâmetros de dados da máquina de indução trifásica:')
Vl = 220  # @param {type:"slider", min:10.0, max:500.0, step:10.0, default:220.0}
print(f"Vl (Tensão RMS de linha) = {Vl} V")

Vl_fase_Y = Vl / np.sqrt(3)
print(f"Vl_fase_Y (Tensão RMS de linha na fase Y) = {Vl_fase_Y:.3f} V")

f = 60.0  # @param {type:"slider", min:10.0, max:120.0, step:1.0, default:60.0}
print(f"f (Frequência) = {f} Hz")
Rs = 0.435  # @param {type:"slider", min:0.1, max:5.0, step:0.01, default:0.435}
print(f"Rs (Resistência do estator) = {Rs} Ω")
Rr = 0.816  # @param {type:"slider", min:0.1, max:5.0, step:0.01, default:0.816}
print(f"Rr (Resistência do rotor) = {Rr} Ω")
Xm = 26.13  # @param {type:"slider", min:1.0, max:100.0, step:0.1, default:26.13}
print(f"Xm (Reatância de magnetização) = {Xm} Ω")
Xls = 0.754  # @param {type:"slider", min:0.1, max:5.0, step:0.01, default:0.754}
print(f"Xls (Reatância de dispersão do estator) = {Xls} Ω")
Xlr = 0.754  # @param {type:"slider", min:0.1, max:5.0, step:0.01, default:0.754}
print(f"Xlr (Reatância de dispersão do rotor) = {Xlr} Ω")
p = 4  # @param {type:"slider", min:2, max:8, step:2, default:4}
print(f"p (Número de polos) = {p}")
J = 0.089  # @param {type:"slider", min:0.01, max:1.0, step:0.001, default:0.089}
print(f"J (Inércia do rotor) = {J} kg·m²")
Tl_initial = 0.0  # @param {type:"slider", min:0.0, max:200.0, step:1.0, default:0.0}
print(f"Tl_initial (Torque inicial) = {Tl_initial} Nm")
Tl_final = 80  # @param {type:"slider", min:0.0, max:200.0, step:1.0, default:80.0}
print(f"Tl_final (Torque final) = {Tl_final} Nm")
# Torque final nulo pois consideraremos a máquina apenas em vazio.
B = 0.0  # @param {type:"slider", min:0.0, max:1.0, step:0.001, default:0.0}
print(f"B (Campo magnético inicial) = {B} Nm·s/rad")


## Park Transform Reference Option (using @param for interactive input)
print('\nEscolha a velocidade angular de referência para a transformada de Park:')
ref_choice = "referência síncrona (we)"  # @param ["referência síncrona (we)", "referência rotórica (wr)", "referência estacionária (0)"]
if ref_choice == "referência síncrona (we)":
    ref = 1
elif ref_choice == "referência rotórica (wr)":
    ref = 2
else:
    ref = 3

if mop == 1:
    print("\nModo de operação: motor")
    Tl = Tl_initial
    Tl_2 = Tl_final
else:
    print("\nModo de operação: gerador conectado ao barramento infinito")
    Tl = -Tl_initial
    Tl_2 = -Tl_final

if ref == 1:
    print('Referência: síncrona (we)')
elif ref == 2:
    print('Referência: rotórica (wr)')
else:
    print('Referência: estacionária (0)')


# Definição das variáveis para iteração
PSIqs_initial = 0
PSIds_initial = 0
PSIqr_initial = 0
PSIdr_initial = 0
wr_initial = 0 # @param {"type":"slider","min":0,"max":3600,"step":50}
# Na partida, a rotação do eixo é nula.
initial_states = [PSIqs_initial, PSIds_initial, PSIqr_initial, PSIdr_initial, wr_initial]

# @title Simulador Y−Δ (Estrela-Triângulo)

# Cálculo de parâmetros
Xml = 1 / ((1 / Xm) + (1 / Xls) + (1 / Xlr))
wb = 2 * np.pi * f  # Base angular velocity
Vqr_squirrel_cage = 0
Vdr_squirrel_cage = 0 # Squirrel cage rotor

## State-Space Representation and ODEs
def induction_motor_equations(states, t, Vqs_t, Vds_t, current_Tl, w_ref_val):
    PSIqs, PSIds, PSIqr, PSIdr, wr = states

    # Dependent variables calculation
    PSImq = Xml * (PSIqs / Xls + PSIqr / Xlr)
    PSImd = Xml * (PSIds / Xls + PSIdr / Xlr)
    ids_val = (1 / Xls) * (PSIds - PSImd)
    iqs_val = (1 / Xls) * (PSIqs - PSImq)

    # Differential equations
    dPSIqs_dt = wb * (Vqs_t - (w_ref_val / wb) * PSIds + (Rs / Xls) * (PSImq - PSIqs))
    dPSIds_dt = wb * (Vds_t + (w_ref_val / wb) * PSIqs + (Rs / Xls) * (PSImd - PSIds))
    dPSIqr_dt = wb * (Vqr_squirrel_cage - ((w_ref_val - wr) / wb) * PSIdr + (Rr / Xlr) * (PSImq - PSIqr))
    dPSIdr_dt = wb * (Vdr_squirrel_cage + ((w_ref_val - wr) / wb) * PSIqr + (Rr / Xlr) * (PSImd - PSIdr))

    # Electromagnetic torque
    Tem_val = (3 / 2) * (p / 2) * (1 / wb) * (PSIds * iqs_val - PSIqs * ids_val)
    dwr_dt = (p / (2 * J)) * (Tem_val - current_Tl) - (B / J) * wr

    return [dPSIqs_dt, dPSIds_dt, dPSIqr_dt, dPSIdr_dt, dwr_dt]

## Simulation Loop (using odeint for integration)
t_values = np.arange(0, tmax, h)

# Store results
wr_results = []
Te_results = []
n_results = []
ids_results = []
iqs_results = []
idr_results = []
iqr_results = []
ias_results = []
ibs_results = []
ics_results = []
iar_results = []
ibr_results = []
icr_results = []
Va_results = []
Vb_results = []
Vc_results = []
Vds_results = []
Vqs_results = []

# To store the last `wr` value for `w_ref_val` if `ref == 2`
last_wr = wr_initial

for i, t_val in enumerate(t_values):
    # Determine mechanical torque
    if t_val >= t_2:
        V_aplicada = Vl
    else:
        current_Tl = Tl
        V_aplicada = Vl_fase_Y

    if t_val >= t_carga:
        current_Tl = Tl_2


    # Stator electrical components
    we_val = 2 * np.pi * f
    tetae = we_val * t_val

    # Define arbitrary reference for the transform based on input choice
    if ref == 1:
        w_ref_val = we_val
    elif ref == 2:
        w_ref_val = last_wr  # Use the last calculated wr
    else:
        w_ref_val = 0

    # Input voltage (infinite bus)
    Va_val = np.sqrt(2) * V_aplicada * np.sin(tetae)
    Vb_val = np.sqrt(2) * V_aplicada * np.sin(tetae - ((2 * np.pi) / 3))
    Vc_val = np.sqrt(2) * V_aplicada * np.sin(tetae + ((2 * np.pi) / 3))

    Vaf_val = np.sqrt(3 / 2) * (Va_val + (-1 / 2) * Vb_val + (-1 / 2) * Vc_val)
    Vbt_val = np.sqrt(3 / 2) * (0 * Va_val + (np.sqrt(3) / 2) * Vb_val + (-np.sqrt(3) / 2) * Vc_val)

    Vds_val = np.cos(tetae) * Vaf_val + np.sin(tetae) * Vbt_val
    Vqs_val = -np.sin(tetae) * Vaf_val + np.cos(tetae) * Vbt_val

    # Integrate one step using odeint
    sol = odeint(induction_motor_equations, initial_states, [t_val, t_val + h], args=(Vqs_val, Vds_val, current_Tl, w_ref_val))
    PSIqs, PSIds, PSIqr, PSIdr, wr = sol[1] # Take the results at t_val + h
    initial_states = [PSIqs, PSIds, PSIqr, PSIdr, wr] # Update initial states for next iteration
    last_wr = wr # Update last_wr for next iteration if ref == 2

    # Store mechanical angular velocity
    wr_results.append(wr)

    # Calculate and store speed in RPM
    n = (120 / p) * (wr / (2 * np.pi))
    n_results.append(n)

    # Calculate currents and store
    PSImd = Xml * (PSIds / Xls + PSIdr / Xlr)
    PSImq = Xml * (PSIqs / Xls + PSIqr / Xlr)

    ids = (1 / Xls) * (PSIds - PSImd)
    iqs = (1 / Xls) * (PSIqs - PSImq)
    idr = (1 / Xlr) * (PSIdr - PSImd)
    iqr = (1 / Xlr) * (PSIqr - PSImq)

    ids_results.append(ids)
    iqs_results.append(iqs)
    idr_results.append(idr)
    iqr_results.append(iqr)

    # Calculate and store electromagnetic torque
    Te = (3 / 2) * (p / 2) * (1 / wb) * (PSIds * iqs - PSIqs * ids)
    Te_results.append(Te)

    # Stator and Rotor currents (alpha-beta and abc)
    tetar = wr * t_val # Using t_val for tetar calculation here, consistent with Scilab code

    iafs = np.cos(tetae) * ids - np.sin(tetae) * iqs
    ibts = np.sin(tetae) * ids + np.cos(tetae) * iqs

    iafr = np.cos(tetar) * idr - np.sin(tetar) * iqr
    ibtr = np.sin(tetar) * idr + np.cos(tetar) * iqr # Corrected to tetar, assuming original was a typo

    ias = np.sqrt(3/2) * (1 * iafs + 0 * ibts)
    ibs = np.sqrt(3/2) * ((-1/2) * iafs + (np.sqrt(3)/2) * ibts)
    ics = np.sqrt(3/2) * ((-1/2) * iafs + (-np.sqrt(3)/2) * ibts)

    iar = np.sqrt(3/2) * (1 * iafr + 0 * ibtr)
    ibr = np.sqrt(3/2) * ((-1/2) * iafr + (np.sqrt(3)/2) * ibtr)
    icr = np.sqrt(3/2) * ((-1/2) * iafr + (-np.sqrt(3)/2) * ibtr)

    ias_results.append(ias)
    ibs_results.append(ibs)
    ics_results.append(ics)
    iar_results.append(iar)
    ibr_results.append(ibr)
    icr_results.append(icr)

    Va_results.append(Va_val)
    Vb_results.append(Vb_val)
    Vc_results.append(Vc_val)
    Vds_results.append(Vds_val)
    Vqs_results.append(Vqs_val)


# Convert lists to numpy arrays for easier plotting
wr_results = np.array(wr_results)
Te_results = np.array(Te_results)
n_results = np.array(n_results)
ids_results = np.array(ids_results)
iqs_results = np.array(iqs_results)
idr_results = np.array(idr_results)
iqr_results = np.array(iqr_results)
ias_results = np.array(ias_results)
ibs_results = np.array(ibs_results)
ics_results = np.array(ics_results)
iar_results = np.array(iar_results)
ibr_results = np.array(ibr_results)
icr_results = np.array(icr_results)
Va_results = np.array(Va_results)
Vb_results = np.array(Vb_results)
Vc_results = np.array(Vc_results)
Vds_results = np.array(Vds_results)
Vqs_results = np.array(Vqs_results)


## Steady-State Values
print("\nValores (finais) em regime permanente das variáveis:")
print("s f_r ids iqs n")
# Assuming the last values are steady-state
s_ss = (wb - wr_results[-1]) / wb
fr_ss = wr_results[-1] / (2 * np.pi)
ids_ss = ids_results[-1]
iqs_ss = iqs_results[-1]
n_ss = n_results[-1]
print(f"{s_ss:.4f} {fr_ss:.4f} {ids_ss:.4f} {iqs_ss:.4f} {n_ss:.4f}")

# Torque
plt.figure(figsize=(10, 4))
plt.subplot(2, 1, 1)
plt.plot(t_values, Te_results, label='$T_e$')
plt.title('$T_e$', fontsize=14)
plt.xlabel('tempo (segundos)', fontsize=12)
plt.ylabel('Torque (Nm)', fontsize=12)
plt.legend(loc='center left', bbox_to_anchor=(1.0, 0.5))  # legenda fora
plt.grid(True)

# Velocidade
plt.figure(figsize=(10, 4))
plt.subplot(2, 1, 2)
plt.plot(t_values, n_results, label='n (RPM)')
plt.title('n (RPM)', fontsize=14)
plt.xlabel('tempo (segundos)', fontsize=12)
plt.ylabel('Velocidade (RPM)', fontsize=12)
plt.legend(loc='center left', bbox_to_anchor=(1.0, 0.5))  # legenda fora
plt.grid(True)
plt.show()

# Stator Voltages
plt.figure(figsize=(10, 4))
plt.subplot(2, 1, 1)
plt.plot(t_values, Va_results, label='$V_a$')
plt.plot(t_values, Vb_results, label='$V_b$')
plt.plot(t_values, Vc_results, label='$V_c$')
plt.title('$V_a$ x $V_b$ x $V_c$', fontsize=14)
plt.xlabel('tempo (segundos)', fontsize=12)
plt.ylabel('Tensão (V)', fontsize=12)
plt.legend(loc='center left', bbox_to_anchor=(1.0, 0.5))
plt.grid(True)

# Stator Currents
plt.figure(figsize=(10, 4))
plt.subplot(2, 1, 2)
plt.plot(t_values, ias_results, label='$i_{as}$')
plt.plot(t_values, ibs_results, label='$i_{bs}$')
plt.plot(t_values, ics_results, label='$i_{cs}$')
plt.title('$I_{as}$ x $I_{bs}$ x $I_{cs}$', fontsize=14)
plt.xlabel('tempo (segundos)', fontsize=12)
plt.ylabel('Corrente (A)', fontsize=12)
plt.legend(loc='center left', bbox_to_anchor=(1.0, 0.5))
plt.grid(True)
plt.tight_layout()
plt.show()

# Rotor Currents
plt.figure(figsize=(10, 4))
plt.subplot(2, 1, 1)
plt.plot(t_values, iar_results, label='$i_{ar}$')
plt.plot(t_values, ibr_results, label='$i_{br}$')
plt.plot(t_values, icr_results, label='$i_{cr}$')
plt.title('$I_{ar}$ x $I_{br}$ x $I_{cr}$', fontsize=14)
plt.xlabel('tempo (segundos)', fontsize=12)
plt.ylabel('Corrente (A)', fontsize=12)
plt.legend(loc='center left', bbox_to_anchor=(1.0, 0.5))
plt.grid(True)
plt.tight_layout()
plt.show()

# @title Resultados e comparação
print('Valores máximos para partida Y−Δ (Estrela-Triângulo)')

# Valores máximos
valores_max_YD = {
    'Corrente máxima na fase A do Estator (A)': max(ias_results),
    'Corrente máxima na fase B do Estator (A)': max(ibs_results),
    'Corrente máxima na fase C do Estator (A)': max(ics_results),
    'Corrente máxima na fase A do Rotor (A)'  : max(iar_results),
    'Corrente máxima na fase B do Rotor (A)'  : max(ibr_results),
    'Corrente máxima na fase C do Rotor (A)'  : max(icr_results),
    'Torque máximo desenvolvido no eixo (N.m)': max(Te_results),
}

# Comparação e impressão
for item, valor_YD in valores_max_YD.items():
    valor_DOL = valores_max_DOL[item]  # pega o valor correspondente da partida direta
    relacao = valor_YD / valor_DOL * 100
    #diferenca_percentual = (1 - relacao) * 100
    print(f'{item}: {valor_YD:.3f} ({relacao:.1f}% do valor máximo em Partida Direta)')

"""## 3. Partida com Autotransformador (Compensadora)

**Objetivo:** Simular a partida com um autotransformador para reduzir a tensão de partida.

**Considerações:**  
Similar à Y−Δ, a partida compensadora é simulada reduzindo a tensão de entrada para um percentual (ex: 50% ou 70%) por um tempo, e depois aumentando para a tensão nominal.

**Configuração:**

- **Modo de Operação:** Motor  
- **Tensão RMS de entrada** ($V_L$): Iniciar com 110.0 V ($220 \times 0.5$) por um tempo (ex: 0.5 s), depois alterar para 220.0 V  
- **Frequência** ($f$): 60.0 Hz  
- **Torque mecânico inicial** ($T_{l\_initial}$): 0.0 Nm  
- **Torque mecânico final** ($T_{l\_final}$): 80.0 Nm  
- **Tempo de aplicação do torque mecânico** ($t_2$): 0.1 s  
- **Referência para a transformada de Park:** Síncrona ($\omega_e$)

**Análise Esperada:**  
Comparar os perfis de corrente e torque com as partidas direta e Y−Δ, notando a redução dependendo do percentual de tensão aplicado.
## 3.1. Alterações a serem feitas:
Similar ao Y-D. O valor inicial da tensão deve ser menor que o nominal

"""

# @title Parâmetros de simulação para partida Compensadora
print('Simulação de máquina de indução gaiola de esquilo trifásica')
print('Partida Compensadora')

## Simulation Parameters (using @param for interactive input)
print('\nParâmetros de simulação:')
tmax = 2  # @param {type:"slider", min:0.1, max:10.0, step:0.1, default:2.0}
print(f"tmax (Tempo de simulação) = {tmax} s")
h = 0.001  # @param {type:"slider", min:0.00001, max:0.001, step:0.00001, default:0.0001}
t_2 = 0.5  # @param {type:"slider", min:0.1, max:5.0, step:0.1, default:1.0}
t_carga = 0.1 # s (Momento em que a carga é aplicada)
print(f"t_carga (Tempo de aplicação da carga) = {t_carga} s")
print(f"t_2 (Tempo de para ação da compensação) = {t_2} s")

## Motor Operation Mode (using @param for interactive input)
print('\nModo de operação da máquina de indução:')
mop_choice = "Motor"  # @param ["Motor", "Gerador conectado ao barramento infinito"]
mop = 1 if mop_choice == "Motor" else 2

## Three-Phase Induction Machine Simulation Parameters (using @param for interactive input)
print('\nParâmetros de dados da máquina de indução trifásica:')
Vl = 220  # @param {type:"slider", min:10.0, max:500.0, step:10.0, default:220.0}
print(f"Vl (Tensão RMS de linha) = {Vl} V")
Regulação_tensão = 0.5 # @param {type:"slider", min:0.1, max:1, step:0.01, default:0.5}
Vl_aplicada_inicialmente = Vl * Regulação_tensão
print(f"Vl_aplicada_inicialmente (Tensão RMS aplicada incialmente) = {Vl_fase_Y:.3f} V")

f = 60.0  # @param {type:"slider", min:10.0, max:120.0, step:1.0, default:60.0}
print(f"f (Frequência) = {f} Hz")
Rs = 0.435  # @param {type:"slider", min:0.1, max:5.0, step:0.01, default:0.435}
print(f"Rs (Resistência do estator) = {Rs} Ω")
Rr = 0.816  # @param {type:"slider", min:0.1, max:5.0, step:0.01, default:0.816}
print(f"Rr (Resistência do rotor) = {Rr} Ω")
Xm = 26.13  # @param {type:"slider", min:1.0, max:100.0, step:0.1, default:26.13}
print(f"Xm (Reatância de magnetização) = {Xm} Ω")
Xls = 0.754  # @param {type:"slider", min:0.1, max:5.0, step:0.01, default:0.754}
print(f"Xls (Reatância de dispersão do estator) = {Xls} Ω")
Xlr = 0.754  # @param {type:"slider", min:0.1, max:5.0, step:0.01, default:0.754}
print(f"Xlr (Reatância de dispersão do rotor) = {Xlr} Ω")
p = 4  # @param {type:"slider", min:2, max:8, step:2, default:4}
print(f"p (Número de polos) = {p}")
J = 0.089  # @param {type:"slider", min:0.01, max:1.0, step:0.001, default:0.089}
print(f"J (Inércia do rotor) = {J} kg·m²")
Tl_initial = 0.0  # @param {type:"slider", min:0.0, max:200.0, step:1.0, default:0.0}
print(f"Tl_initial (Torque inicial) = {Tl_initial} Nm")
Tl_final = 80  # @param {type:"slider", min:0.0, max:200.0, step:1.0, default:80.0}
print(f"Tl_final (Torque final) = {Tl_final} Nm")
# Torque final nulo pois consideraremos a máquina apenas em vazio.
B = 0.0  # @param {type:"slider", min:0.0, max:1.0, step:0.001, default:0.0}
print(f"B (Campo magnético inicial) = {B} Nm·s/rad")


## Park Transform Reference Option (using @param for interactive input)
print('\nEscolha a velocidade angular de referência para a transformada de Park:')
ref_choice = "referência síncrona (we)"  # @param ["referência síncrona (we)", "referência rotórica (wr)", "referência estacionária (0)"]
if ref_choice == "referência síncrona (we)":
    ref = 1
elif ref_choice == "referência rotórica (wr)":
    ref = 2
else:
    ref = 3

if mop == 1:
    print("\nModo de operação: motor")
    Tl = Tl_initial
    Tl_2 = Tl_final
else:
    print("\nModo de operação: gerador conectado ao barramento infinito")
    Tl = -Tl_initial
    Tl_2 = -Tl_final

if ref == 1:
    print('Referência: síncrona (we)')
elif ref == 2:
    print('Referência: rotórica (wr)')
else:
    print('Referência: estacionária (0)')


# Definição das variáveis para iteração
PSIqs_initial = 0
PSIds_initial = 0
PSIqr_initial = 0
PSIdr_initial = 0
wr_initial = 0 # @param {"type":"slider","min":0,"max":3600,"step":50}
# Na partida, a rotação do eixo é nula.
initial_states = [PSIqs_initial, PSIds_initial, PSIqr_initial, PSIdr_initial, wr_initial]

# @title Simulador

# Cálculo de parâmetros
Xml = 1 / ((1 / Xm) + (1 / Xls) + (1 / Xlr))
wb = 2 * np.pi * f  # Base angular velocity
Vqr_squirrel_cage = 0
Vdr_squirrel_cage = 0 # Squirrel cage rotor

## State-Space Representation and ODEs
def induction_motor_equations(states, t, Vqs_t, Vds_t, current_Tl, w_ref_val):
    PSIqs, PSIds, PSIqr, PSIdr, wr = states

    # Dependent variables calculation
    PSImq = Xml * (PSIqs / Xls + PSIqr / Xlr)
    PSImd = Xml * (PSIds / Xls + PSIdr / Xlr)
    ids_val = (1 / Xls) * (PSIds - PSImd)
    iqs_val = (1 / Xls) * (PSIqs - PSImq)

    # Differential equations
    dPSIqs_dt = wb * (Vqs_t - (w_ref_val / wb) * PSIds + (Rs / Xls) * (PSImq - PSIqs))
    dPSIds_dt = wb * (Vds_t + (w_ref_val / wb) * PSIqs + (Rs / Xls) * (PSImd - PSIds))
    dPSIqr_dt = wb * (Vqr_squirrel_cage - ((w_ref_val - wr) / wb) * PSIdr + (Rr / Xlr) * (PSImq - PSIqr))
    dPSIdr_dt = wb * (Vdr_squirrel_cage + ((w_ref_val - wr) / wb) * PSIqr + (Rr / Xlr) * (PSImd - PSIdr))

    # Electromagnetic torque
    Tem_val = (3 / 2) * (p / 2) * (1 / wb) * (PSIds * iqs_val - PSIqs * ids_val)
    dwr_dt = (p / (2 * J)) * (Tem_val - current_Tl) - (B / J) * wr

    return [dPSIqs_dt, dPSIds_dt, dPSIqr_dt, dPSIdr_dt, dwr_dt]

## Simulation Loop (using odeint for integration)
t_values = np.arange(0, tmax, h)

# Store results
wr_results = []
Te_results = []
n_results = []
ids_results = []
iqs_results = []
idr_results = []
iqr_results = []
ias_results = []
ibs_results = []
ics_results = []
iar_results = []
ibr_results = []
icr_results = []
Va_results = []
Vb_results = []
Vc_results = []
Vds_results = []
Vqs_results = []

# To store the last `wr` value for `w_ref_val` if `ref == 2`
last_wr = wr_initial

for i, t_val in enumerate(t_values):
    # Determine mechanical torque
    if t_val >= t_2:
        V_aplicada = Vl
    else:
        current_Tl = Tl
        V_aplicada = Vl_aplicada_inicialmente

    if t_val >= t_carga:
        current_Tl = Tl_2


    # Stator electrical components
    we_val = 2 * np.pi * f
    tetae = we_val * t_val

    # Define arbitrary reference for the transform based on input choice
    if ref == 1:
        w_ref_val = we_val
    elif ref == 2:
        w_ref_val = last_wr  # Use the last calculated wr
    else:
        w_ref_val = 0

    # Input voltage (infinite bus)
    Va_val = np.sqrt(2) * V_aplicada * np.sin(tetae)
    Vb_val = np.sqrt(2) * V_aplicada * np.sin(tetae - ((2 * np.pi) / 3))
    Vc_val = np.sqrt(2) * V_aplicada * np.sin(tetae + ((2 * np.pi) / 3))

    Vaf_val = np.sqrt(3 / 2) * (Va_val + (-1 / 2) * Vb_val + (-1 / 2) * Vc_val)
    Vbt_val = np.sqrt(3 / 2) * (0 * Va_val + (np.sqrt(3) / 2) * Vb_val + (-np.sqrt(3) / 2) * Vc_val)

    Vds_val = np.cos(tetae) * Vaf_val + np.sin(tetae) * Vbt_val
    Vqs_val = -np.sin(tetae) * Vaf_val + np.cos(tetae) * Vbt_val

    # Integrate one step using odeint
    sol = odeint(induction_motor_equations, initial_states, [t_val, t_val + h], args=(Vqs_val, Vds_val, current_Tl, w_ref_val))
    PSIqs, PSIds, PSIqr, PSIdr, wr = sol[1] # Take the results at t_val + h
    initial_states = [PSIqs, PSIds, PSIqr, PSIdr, wr] # Update initial states for next iteration
    last_wr = wr # Update last_wr for next iteration if ref == 2

    # Store mechanical angular velocity
    wr_results.append(wr)

    # Calculate and store speed in RPM
    n = (120 / p) * (wr / (2 * np.pi))
    n_results.append(n)

    # Calculate currents and store
    PSImd = Xml * (PSIds / Xls + PSIdr / Xlr)
    PSImq = Xml * (PSIqs / Xls + PSIqr / Xlr)

    ids = (1 / Xls) * (PSIds - PSImd)
    iqs = (1 / Xls) * (PSIqs - PSImq)
    idr = (1 / Xlr) * (PSIdr - PSImd)
    iqr = (1 / Xlr) * (PSIqr - PSImq)

    ids_results.append(ids)
    iqs_results.append(iqs)
    idr_results.append(idr)
    iqr_results.append(iqr)

    # Calculate and store electromagnetic torque
    Te = (3 / 2) * (p / 2) * (1 / wb) * (PSIds * iqs - PSIqs * ids)
    Te_results.append(Te)

    # Stator and Rotor currents (alpha-beta and abc)
    tetar = wr * t_val # Using t_val for tetar calculation here, consistent with Scilab code

    iafs = np.cos(tetae) * ids - np.sin(tetae) * iqs
    ibts = np.sin(tetae) * ids + np.cos(tetae) * iqs

    iafr = np.cos(tetar) * idr - np.sin(tetar) * iqr
    ibtr = np.sin(tetar) * idr + np.cos(tetar) * iqr # Corrected to tetar, assuming original was a typo

    ias = np.sqrt(3/2) * (1 * iafs + 0 * ibts)
    ibs = np.sqrt(3/2) * ((-1/2) * iafs + (np.sqrt(3)/2) * ibts)
    ics = np.sqrt(3/2) * ((-1/2) * iafs + (-np.sqrt(3)/2) * ibts)

    iar = np.sqrt(3/2) * (1 * iafr + 0 * ibtr)
    ibr = np.sqrt(3/2) * ((-1/2) * iafr + (np.sqrt(3)/2) * ibtr)
    icr = np.sqrt(3/2) * ((-1/2) * iafr + (-np.sqrt(3)/2) * ibtr)

    ias_results.append(ias)
    ibs_results.append(ibs)
    ics_results.append(ics)
    iar_results.append(iar)
    ibr_results.append(ibr)
    icr_results.append(icr)

    Va_results.append(Va_val)
    Vb_results.append(Vb_val)
    Vc_results.append(Vc_val)
    Vds_results.append(Vds_val)
    Vqs_results.append(Vqs_val)


# Convert lists to numpy arrays for easier plotting
wr_results = np.array(wr_results)
Te_results = np.array(Te_results)
n_results = np.array(n_results)
ids_results = np.array(ids_results)
iqs_results = np.array(iqs_results)
idr_results = np.array(idr_results)
iqr_results = np.array(iqr_results)
ias_results = np.array(ias_results)
ibs_results = np.array(ibs_results)
ics_results = np.array(ics_results)
iar_results = np.array(iar_results)
ibr_results = np.array(ibr_results)
icr_results = np.array(icr_results)
Va_results = np.array(Va_results)
Vb_results = np.array(Vb_results)
Vc_results = np.array(Vc_results)
Vds_results = np.array(Vds_results)
Vqs_results = np.array(Vqs_results)


## Steady-State Values
print("\nValores (finais) em regime permanente das variáveis:")
print("s f_r ids iqs n")
# Assuming the last values are steady-state
s_ss = (wb - wr_results[-1]) / wb
fr_ss = wr_results[-1] / (2 * np.pi)
ids_ss = ids_results[-1]
iqs_ss = iqs_results[-1]
n_ss = n_results[-1]
print(f"{s_ss:.4f} {fr_ss:.4f} {ids_ss:.4f} {iqs_ss:.4f} {n_ss:.4f}")

# Torque
plt.figure(figsize=(10, 4))
plt.subplot(2, 1, 1)
plt.plot(t_values, Te_results, label='$T_e$')
plt.title('$T_e$', fontsize=14)
plt.xlabel('tempo (segundos)', fontsize=12)
plt.ylabel('Torque (Nm)', fontsize=12)
plt.legend(loc='center left', bbox_to_anchor=(1.0, 0.5))  # legenda fora
plt.grid(True)

# Velocidade
plt.figure(figsize=(10, 4))
plt.subplot(2, 1, 2)
plt.plot(t_values, n_results, label='n (RPM)')
plt.title('n (RPM)', fontsize=14)
plt.xlabel('tempo (segundos)', fontsize=12)
plt.ylabel('Velocidade (RPM)', fontsize=12)
plt.legend(loc='center left', bbox_to_anchor=(1.0, 0.5))  # legenda fora
plt.grid(True)
plt.show()

# Stator Voltages
plt.figure(figsize=(10, 4))
plt.subplot(2, 1, 1)
plt.plot(t_values, Va_results, label='$V_a$')
plt.plot(t_values, Vb_results, label='$V_b$')
plt.plot(t_values, Vc_results, label='$V_c$')
plt.title('$V_a$ x $V_b$ x $V_c$', fontsize=14)
plt.xlabel('tempo (segundos)', fontsize=12)
plt.ylabel('Tensão (V)', fontsize=12)
plt.legend(loc='center left', bbox_to_anchor=(1.0, 0.5))
plt.grid(True)

# Stator Currents
plt.figure(figsize=(10, 4))
plt.subplot(2, 1, 2)
plt.plot(t_values, ias_results, label='$i_{as}$')
plt.plot(t_values, ibs_results, label='$i_{bs}$')
plt.plot(t_values, ics_results, label='$i_{cs}$')
plt.title('$I_{as}$ x $I_{bs}$ x $I_{cs}$', fontsize=14)
plt.xlabel('tempo (segundos)', fontsize=12)
plt.ylabel('Corrente (A)', fontsize=12)
plt.legend(loc='center left', bbox_to_anchor=(1.0, 0.5))
plt.grid(True)
plt.tight_layout()
plt.show()

# Rotor Currents
plt.figure(figsize=(10, 4))
plt.subplot(2, 1, 1)
plt.plot(t_values, iar_results, label='$i_{ar}$')
plt.plot(t_values, ibr_results, label='$i_{br}$')
plt.plot(t_values, icr_results, label='$i_{cr}$')
plt.title('$I_{ar}$ x $I_{br}$ x $I_{cr}$', fontsize=14)
plt.xlabel('tempo (segundos)', fontsize=12)
plt.ylabel('Corrente (A)', fontsize=12)
plt.legend(loc='center left', bbox_to_anchor=(1.0, 0.5))
plt.grid(True)
plt.tight_layout()
plt.show()

# @title Resultados e comparação
print('Valores máximos para partida com Autotransformador')

# Valores máximos
valores_max_AT = {
    'Corrente máxima na fase A do Estator (A)': max(ias_results),
    'Corrente máxima na fase B do Estator (A)': max(ibs_results),
    'Corrente máxima na fase C do Estator (A)': max(ics_results),
    'Corrente máxima na fase A do Rotor (A)'  : max(iar_results),
    'Corrente máxima na fase B do Rotor (A)'  : max(ibr_results),
    'Corrente máxima na fase C do Rotor (A)'  : max(icr_results),
    'Torque máximo desenvolvido no eixo (N.m)': max(Te_results),
}

# Comparação com DOL e impressão
for item, valor_AT in valores_max_AT.items():
    valor_DOL = valores_max_DOL[item]  # refere-se ao valor correspondente da partida direta
    valor_YD = valores_max_YD[item]  # refere-se ao valor correspondente da partida Y−Δ
    relacao_DOL = valor_AT / valor_DOL * 100
    relacao_YD = valor_AT / valor_YD * 100
    #diferenca_percentual_DOL = (1 - relacao) * 100
    print(f'{item}: {valor_AT:.3f} ({relacao_DOL:.1f}% do valor máximo em Partida Direta e {relacao_YD:.1f}% do valor máximo em Partida Y−Δ)')

"""## 3. Partida Soft-Starter (Mais ou menos)

**Objetivo:** Simular a partida com um autotransformador para reduzir a tensão de partida.

**Considerações:**  
Similar à Y−Δ, a partida compensadora é simulada reduzindo a tensão de entrada para um percentual (ex: 50% ou 70%) por um tempo, e depois aumentando para a tensão nominal.

**Configuração:**

- **Modo de Operação:** Motor  
- **Tensão RMS de entrada** ($V_L$): Iniciar com 110.0 V ($220 \times 0.5$) por um tempo (ex: 0.5 s), depois alterar para 220.0 V  
- **Frequência** ($f$): 60.0 Hz  
- **Torque mecânico inicial** ($T_{l\_initial}$): 0.0 Nm  
- **Torque mecânico final** ($T_{l\_final}$): 80.0 Nm  
- **Tempo de aplicação do torque mecânico** ($t_2$): 0.1 s  
- **Referência para a transformada de Park:** Síncrona ($\omega_e$)

**Análise Esperada:**  
Comparar os perfis de corrente e torque com as partidas direta e Y−Δ, notando a redução dependendo do percentual de tensão aplicado.

"""

# @title Parâmetros de simulação para Soft-Starter
print('Simulação de máquina de indução gaiola de esquilo trifásica')
print('Partida Soft-Starter')

# Simulation Parameters (using @param for interactive input)
print('\nParâmetros de simulação:')
tmax = 10  # @param {type:"slider", min:0.1, max:10.0, step:0.1, default:2.0}
h = 0.001  # @param {type:"slider", min:0.00001, max:0.001, step:0.00001, default:0.0001}
t_2 = 0.9  # @param {type:"slider", min:0.1, max:5.0, step:0.1, default:1.0}
t_pico = 5  # @param {type:"slider", min:1, max:10, step:0.1, default:1.0}
# Tempo em que a tensão aplicada deve ser igual a nominal
t_carga = 0.1 # @param {type:"slider", min:0, max:10, step:0.1, default:1.0}
# s (Momento em que a carga é aplicada)
print(f"tmax (Tempo de simulação) = {tmax} s")
print(f"t_carga (Tempo de aplicação da carga) = {t_carga} s")
print(f"t_2 (Tempo de alteração da tensão) = {t_2} s")
print(f"t_pico (Tempo de pico) = {t_pico} s")

## Motor Operation Mode (using @param for interactive input)
print('\nModo de operação da máquina de indução:')
mop_choice = "Motor"  # @param ["Motor", "Gerador conectado ao barramento infinito"]
mop = 1 if mop_choice == "Motor" else 2

## Three-Phase Induction Machine Simulation Parameters (using @param for interactive input)
print('\nParâmetros de dados da máquina de indução trifásica:')
Regulação_tensão = 0.5  # @param {type:"slider", min:0, max:1, step:0.01, default:0.5}
Vl = 220  # @param {type:"slider", min:10.0, max:500.0, step:10.0, default:220.0}
Vl_aplicada_inicialmente = Vl * Regulação_tensão
#Valor inicial da tensão
print(f"Valor inicial da tensão (Tensão RMS de linha) = {Vl_aplicada_inicialmente} V")
print(f"Vl (Tensão Nominal RMS de linha) = {Vl} V")
f = 60  # @param {type:"slider", min:10.0, max:120.0, step:1.0, default:60.0}
print(f"f (Frequência) = {f} Hz")
Rs = 0.435  # @param {type:"slider", min:0.1, max:5.0, step:0.01, default:0.435}
print(f"Rs (Resistência do estator) = {Rs} Ω")
Rr = 0.816  # @param {type:"slider", min:0.1, max:5.0, step:0.01, default:0.816}
print(f"Rr (Resistência do rotor) = {Rr} Ω")
Xm = 26.13  # @param {type:"slider", min:1.0, max:100.0, step:0.1, default:26.13}
print(f"Xm (Reatância de magnetização) = {Xm} Ω")
Xls = 0.754  # @param {type:"slider", min:0.1, max:5.0, step:0.01, default:0.754}
print(f"Xls (Reatância de dispersão do estator) = {Xls} Ω")
Xlr = 0.754  # @param {type:"slider", min:0.1, max:5.0, step:0.01, default:0.754}
print(f"Xlr (Reatância de dispersão do rotor) = {Xlr} Ω")
p = 4  # @param {type:"slider", min:2, max:8, step:2, default:4}
print(f"p (Número de polos) = {p}")
J = 0.089  # @param {type:"slider", min:0.01, max:1.0, step:0.001, default:0.089}
print(f"J (Inércia do rotor) = {J} kg·m²")
Tl_initial = 0.0  # @param {type:"slider", min:0.0, max:200.0, step:1.0, default:0.0}
print(f"Tl_initial (Torque inicial) = {Tl_initial} Nm")
Tl_final = 80  # @param {type:"slider", min:0.0, max:200.0, step:1.0, default:80.0}
print(f"Tl_final (Torque final) = {Tl_final} Nm")
# Torque final nulo pois consideraremos a máquina apenas em vazio.
B = 0.0  # @param {type:"slider", min:0.0, max:1.0, step:0.001, default:0.0}
print(f"B (Campo magnético inicial) = {B} Nm·s/rad")


## Park Transform Reference Option (using @param for interactive input)
print('\nEscolha a velocidade angular de referência para a transformada de Park:')
ref_choice = "referência síncrona (we)"  # @param ["referência síncrona (we)", "referência rotórica (wr)", "referência estacionária (0)"]
if ref_choice == "referência síncrona (we)":
    ref = 1
elif ref_choice == "referência rotórica (wr)":
    ref = 2
else:
    ref = 3

if mop == 1:
    print("\nModo de operação: motor")
    Tl = Tl_initial
    Tl_2 = Tl_final
else:
    print("\nModo de operação: gerador conectado ao barramento infinito")
    Tl = -Tl_initial
    Tl_2 = -Tl_final

if ref == 1:
    print('Referência: síncrona (we)')
elif ref == 2:
    print('Referência: rotórica (wr)')
else:
    print('Referência: estacionária (0)')


# Definição das variáveis para iteração
PSIqs_initial = 0
PSIds_initial = 0
PSIqr_initial = 0
PSIdr_initial = 0
wr_initial    = 0 # @param {"type":"slider","min":0,"max":3600,"step":50}
# Na partida, a rotação do eixo é nula.
initial_states = [PSIqs_initial, PSIds_initial, PSIqr_initial, PSIdr_initial, wr_initial]

# @title Simulador de partida Soft-Starter

# Cálculo de parâmetros
Xml = 1 / ((1 / Xm) + (1 / Xls) + (1 / Xlr))
wb = 2 * np.pi * f  # Base angular velocity
Vqr_squirrel_cage = 0
Vdr_squirrel_cage = 0 # Squirrel cage rotor

## State-Space Representation and ODEs
def induction_motor_equations(states, t, Vqs_t, Vds_t, current_Tl, w_ref_val):
    PSIqs, PSIds, PSIqr, PSIdr, wr = states

    # Dependent variables calculation
    PSImq = Xml * (PSIqs / Xls + PSIqr / Xlr)
    PSImd = Xml * (PSIds / Xls + PSIdr / Xlr)
    ids_val = (1 / Xls) * (PSIds - PSImd)
    iqs_val = (1 / Xls) * (PSIqs - PSImq)

    # Differential equations
    dPSIqs_dt = wb * (Vqs_t - (w_ref_val / wb) * PSIds + (Rs / Xls) * (PSImq - PSIqs))
    dPSIds_dt = wb * (Vds_t + (w_ref_val / wb) * PSIqs + (Rs / Xls) * (PSImd - PSIds))
    dPSIqr_dt = wb * (Vqr_squirrel_cage - ((w_ref_val - wr) / wb) * PSIdr + (Rr / Xlr) * (PSImq - PSIqr))
    dPSIdr_dt = wb * (Vdr_squirrel_cage + ((w_ref_val - wr) / wb) * PSIqr + (Rr / Xlr) * (PSImd - PSIdr))

    # Electromagnetic torque
    Tem_val = (3 / 2) * (p / 2) * (1 / wb) * (PSIds * iqs_val - PSIqs * ids_val)
    dwr_dt = (p / (2 * J)) * (Tem_val - current_Tl) - (B / J) * wr

    return [dPSIqs_dt, dPSIds_dt, dPSIqr_dt, dPSIdr_dt, dwr_dt]

## Simulation Loop (using odeint for integration)
t_values = np.arange(0, tmax, h)

# Store results
wr_results  = []
Te_results  = []
n_results   = []
ids_results = []
iqs_results = []
idr_results = []
iqr_results = []
ias_results = []
ibs_results = []
ics_results = []
iar_results = []
ibr_results = []
icr_results = []
Va_results  = []
Vb_results  = []
Vc_results  = []
Vds_results = []
Vqs_results = []

# To store the last `wr` value for `w_ref_val` if `ref == 2`
last_wr = wr_initial

for i, t_val in enumerate(t_values):
    # Determine mechanical torque
    if t_val < t_2:
       V_apli = Vl_aplicada_inicialmente
    elif t_val >= t_2 and t_val < t_pico:
       V_apli = Vl_aplicada_inicialmente + (Vl - Vl_aplicada_inicialmente) * (t_val - t_2) / (t_pico - t_2) # A tensão aplicada cresce linearmente com relação ao tempo.
    else:
       V_apli = Vl

    if t_val >= t_carga:
        current_Tl = Tl_2
    else:
      current_Tl = Tl


    # Stator electrical components
    we_val = 2 * np.pi * f
    tetae = we_val * t_val

    # Define arbitrary reference for the transform based on input choice
    if ref == 1:
        w_ref_val = we_val
    elif ref == 2:
        w_ref_val = last_wr  # Use the last calculated wr
    else:
        w_ref_val = 0

    # Input voltage (infinite bus)
    Va_val = np.sqrt(2) * V_apli * np.sin(tetae)
    Vb_val = np.sqrt(2) * V_apli * np.sin(tetae - ((2 * np.pi) / 3))
    Vc_val = np.sqrt(2) * V_apli * np.sin(tetae + ((2 * np.pi) / 3))

    Vaf_val = np.sqrt(3 / 2) * (Va_val + (-1 / 2) * Vb_val + (-1 / 2) * Vc_val)
    Vbt_val = np.sqrt(3 / 2) * (0 * Va_val + (np.sqrt(3) / 2) * Vb_val + (-np.sqrt(3) / 2) * Vc_val)

    Vds_val = np.cos(tetae) * Vaf_val + np.sin(tetae) * Vbt_val
    Vqs_val = -np.sin(tetae) * Vaf_val + np.cos(tetae) * Vbt_val

    # Integrate one step using odeint
    sol = odeint(induction_motor_equations, initial_states, [t_val, t_val + h], args=(Vqs_val, Vds_val, current_Tl, w_ref_val))
    PSIqs, PSIds, PSIqr, PSIdr, wr = sol[1] # Take the results at t_val + h
    initial_states = [PSIqs, PSIds, PSIqr, PSIdr, wr] # Update initial states for next iteration
    last_wr = wr # Update last_wr for next iteration if ref == 2

    # Store mechanical angular velocity
    wr_results.append(wr)

    # Calculate and store speed in RPM
    n = (120 / p) * (wr / (2 * np.pi))
    n_results.append(n)

    # Calculate currents and store
    PSImd = Xml * (PSIds / Xls + PSIdr / Xlr)
    PSImq = Xml * (PSIqs / Xls + PSIqr / Xlr)

    ids = (1 / Xls) * (PSIds - PSImd)
    iqs = (1 / Xls) * (PSIqs - PSImq)
    idr = (1 / Xlr) * (PSIdr - PSImd)
    iqr = (1 / Xlr) * (PSIqr - PSImq)

    ids_results.append(ids)
    iqs_results.append(iqs)
    idr_results.append(idr)
    iqr_results.append(iqr)

    # Calculate and store electromagnetic torque
    Te = (3 / 2) * (p / 2) * (1 / wb) * (PSIds * iqs - PSIqs * ids)
    Te_results.append(Te)

    # Stator and Rotor currents (alpha-beta and abc)
    tetar = wr * t_val # Using t_val for tetar calculation here, consistent with Scilab code

    iafs = np.cos(tetae) * ids - np.sin(tetae) * iqs
    ibts = np.sin(tetae) * ids + np.cos(tetae) * iqs

    iafr = np.cos(tetar) * idr - np.sin(tetar) * iqr
    ibtr = np.sin(tetar) * idr + np.cos(tetar) * iqr # Corrected to tetar, assuming original was a typo

    ias = np.sqrt(3/2) * (1 * iafs + 0 * ibts)
    ibs = np.sqrt(3/2) * ((-1/2) * iafs + (np.sqrt(3)/2) * ibts)
    ics = np.sqrt(3/2) * ((-1/2) * iafs + (-np.sqrt(3)/2) * ibts)

    iar = np.sqrt(3/2) * (1 * iafr + 0 * ibtr)
    ibr = np.sqrt(3/2) * ((-1/2) * iafr + (np.sqrt(3)/2) * ibtr)
    icr = np.sqrt(3/2) * ((-1/2) * iafr + (-np.sqrt(3)/2) * ibtr)

    ias_results.append(ias)
    ibs_results.append(ibs)
    ics_results.append(ics)
    iar_results.append(iar)
    ibr_results.append(ibr)
    icr_results.append(icr)

    Va_results.append(Va_val)
    Vb_results.append(Vb_val)
    Vc_results.append(Vc_val)
    Vds_results.append(Vds_val)
    Vqs_results.append(Vqs_val)


# Convert lists to numpy arrays for easier plotting
wr_results  = np.array(wr_results)
Te_results  = np.array(Te_results)
n_results   = np.array(n_results)
ids_results = np.array(ids_results)
iqs_results = np.array(iqs_results)
idr_results = np.array(idr_results)
iqr_results = np.array(iqr_results)
ias_results = np.array(ias_results)
ibs_results = np.array(ibs_results)
ics_results = np.array(ics_results)
iar_results = np.array(iar_results)
ibr_results = np.array(ibr_results)
icr_results = np.array(icr_results)
Va_results  = np.array(Va_results)
Vb_results  = np.array(Vb_results)
Vc_results  = np.array(Vc_results)
Vds_results = np.array(Vds_results)
Vqs_results = np.array(Vqs_results)


## Steady-State Values
print("\nValores (finais) em regime permanente das variáveis:")
print("s f_r ids iqs n")
# Assuming the last values are steady-state
s_ss = (wb - wr_results[-1]) / wb
fr_ss = wr_results[-1] / (2 * np.pi)
ids_ss = ids_results[-1]
iqs_ss = iqs_results[-1]
n_ss = n_results[-1]
print(f"{s_ss:.4f} {fr_ss:.4f} {ids_ss:.4f} {iqs_ss:.4f} {n_ss:.4f}")

# Torque
plt.figure(figsize=(10, 4))
plt.subplot(2, 1, 1)
plt.plot(t_values, Te_results, label='$T_e$')
plt.title('$T_e$', fontsize=14)
plt.xlabel('tempo (segundos)', fontsize=12)
plt.ylabel('Torque (Nm)', fontsize=12)
plt.legend(loc='center left', bbox_to_anchor=(1.0, 0.5))  # legenda fora
plt.grid(True)

# Velocidade
plt.figure(figsize=(10, 4))
plt.subplot(2, 1, 2)
plt.plot(t_values, n_results, label='n (RPM)')
plt.title('n (RPM)', fontsize=14)
plt.xlabel('tempo (segundos)', fontsize=12)
plt.ylabel('Velocidade (RPM)', fontsize=12)
plt.legend(loc='center left', bbox_to_anchor=(1.0, 0.5))  # legenda fora
plt.grid(True)
plt.show()

# Stator Voltages
plt.figure(figsize=(10, 4))
plt.subplot(2, 1, 1)
plt.plot(t_values, Va_results, label='$V_a$')
plt.plot(t_values, Vb_results, label='$V_b$')
plt.plot(t_values, Vc_results, label='$V_c$')
plt.title('$V_a$ x $V_b$ x $V_c$', fontsize=14)
plt.xlabel('tempo (segundos)', fontsize=12)
plt.ylabel('Tensão (V)', fontsize=12)
plt.legend(loc='center left', bbox_to_anchor=(1.0, 0.5))
plt.grid(True)

# Stator Currents
plt.figure(figsize=(10, 4))
plt.subplot(2, 1, 2)
plt.plot(t_values, ias_results, label='$i_{as}$')
plt.plot(t_values, ibs_results, label='$i_{bs}$')
plt.plot(t_values, ics_results, label='$i_{cs}$')
plt.title('$I_{as}$ x $I_{bs}$ x $I_{cs}$', fontsize=14)
plt.xlabel('tempo (segundos)', fontsize=12)
plt.ylabel('Corrente (A)', fontsize=12)
plt.legend(loc='center left', bbox_to_anchor=(1.0, 0.5))
plt.grid(True)
plt.tight_layout()
plt.show()

# Rotor Currents
plt.figure(figsize=(10, 4))
plt.subplot(2, 1, 1)
plt.plot(t_values, iar_results, label='$i_{ar}$')
plt.plot(t_values, ibr_results, label='$i_{br}$')
plt.plot(t_values, icr_results, label='$i_{cr}$')
plt.title('$I_{ar}$ x $I_{br}$ x $I_{cr}$', fontsize=14)
plt.xlabel('tempo (segundos)', fontsize=12)
plt.ylabel('Corrente (A)', fontsize=12)
plt.legend(loc='center left', bbox_to_anchor=(1.0, 0.5))
plt.grid(True)
plt.tight_layout()
plt.show()

print('Valores máximos para partida Soft-Starter')

# Valores máximos
valores_max_SF = {
    'Corrente máxima na fase A do Estator (A)': max(ias_results),
    'Corrente máxima na fase B do Estator (A)': max(ibs_results),
    'Corrente máxima na fase C do Estator (A)': max(ics_results),
    'Corrente máxima na fase A do Rotor (A)'  : max(iar_results),
    'Corrente máxima na fase B do Rotor (A)'  : max(ibr_results),
    'Corrente máxima na fase C do Rotor (A)'  : max(icr_results),
    'Torque máximo desenvolvido no eixo (N.m)': max(Te_results),
}

for item, valor_SF in valores_max_AT.items():
    valor_DOL = valores_max_DOL[item]  # refere-se ao valor correspondente da partida direta
    valor_YD = valores_max_YD[item]  # refere-se ao valor correspondente da partida Y−Δ
    relacao_DOL = valor_SF / valor_DOL * 100
    relacao_YD = valor_SF / valor_YD * 100
    print(f'{item}: {valor_SF:.3f} ({relacao_DOL:.1f}% do valor máximo em Partida Direta e {relacao_YD:.1f}% do valor máximo em Partida Y−Δ)')