# -*- coding: utf-8 -*-
"""Finalizado - Simulação de Máquina de Indução Trifásica - Experimentos de Parâmetros da Máquina

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JwYfgu5MaMCe4cA09R4rwVwM6YmSFjJV
"""

# @title Bibliotecas
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import odeint
from IPython.display import display

"""---

# O Colab aqui apresentado tem o objetivo de simular situações específicas no funcionamento de uma máquina de indução trifásica.

# **7. Impacto da Resistência Rotórica ( Rr) no Torque de Partida e Escorregamento**
***Objetivo: Entender como a variação de Rr afeta o desempenho da partida e o escorregamento em regime.***

Configuração:

* Modo de Operação: Motor Rr: Variações ( 0.3 Ohm, 1.0 Ohm e 1.2 Ohm)

* Torque mecânico final (Tlfinal): 80.0 Nm

Análise Esperada: Comparar o torque máximo na partida e a velocidade (ou escorregamento) em regime para diferentes valores de  Rr.
"""

# Q7 — Impacto da Resistência Rotórica (Rr) no Torque de Partida e Escorregamento

# PARÂMETROS DA MÁQUINA

p = 4             # nº de polos
f = 60.0          # Hz
V_ll = 220.0      # tensão linha-linha RMS (V)
conn = "Y"        # "Y" (estrela) ou "D" (triângulo)
Rs = 0.435        # ohm
Ls = 0.002        # H (indutância TOTAL de fase do estator)
Lr = 0.002        # H (indutância TOTAL de fase do rotor referido)
Lm = 0.0693       # H (magnetização)
T_load = 80.0     # N·m (torque da carga p/ ponto de operação)

# Valores de Rr:
Rr_list = [0.30, 1.00, 1.20]  # ohm


# IMPLEMENTAÇÃO
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from math import pi, sqrt

def _v_phase(V_ll, conn):
    return V_ll / sqrt(3.0) if str(conn).upper() == "Y" else V_ll

def _split_leak(Ls, Lr, Lm):
    Lls = max(Ls - Lm, 0.0)   # dispersão do estator
    Llr = max(Lr - Lm, 0.0)   # dispersão do rotor
    return Lls, Llr

def _torque_curve_regime(Rr_value, *, p, f, V_ll, conn, Rs, Ls, Lr, Lm, T_load, n_pts=4000):
    # Velocidades síncronas
    w_sync = 4 * pi * f / p       # mecânica (rad/s)
    w_e = 2 * pi * f              # elétrica (rad/s)

    # Tensões/reatâncias
    Vph = _v_phase(V_ll, conn)
    Lls, Llr = _split_leak(Ls, Lr, Lm)
    X1 = w_e * Lls
    X2 = w_e * Llr
    Xm = w_e * Lm

    # Impedâncias do estator e magnetização
    Z1 = complex(Rs, X1)
    Zm = complex(0.0, Xm)

    # Thevenin visto pelo rotor
    Vth = Vph * (Zm / (Z1 + Zm))
    Zth = (Zm * Z1) / (Z1 + Zm)
    Rth, Xth = Zth.real, Zth.imag

    # Varredura de escorregamento (evita s=0)
    s = np.linspace(1e-4, 1.0, n_pts)[::-1]

    # Torque eletromagnético em regime (forma clássica com Thevenin)
    R2 = Rr_value
    num = 3.0 * (abs(Vth)**2) * (R2 / s)
    den = w_sync * ((Rth + (R2 / s))**2 + (Xth + X2)**2)
    Te = num / den  # N·m

    # rpm
    ns_rpm = 120.0 * f / p
    n_rpm = (1 - s) * ns_rpm

    # Métricas
    Te_start = (3.0 * (abs(Vth)**2) * (R2 / 1.0)) / (w_sync * ((Rth + (R2 / 1.0))**2 + (Xth + X2)**2))
    s_Tmax = R2 / np.sqrt(Rth**2 + (Xth + X2)**2)
    s_Tmax = np.clip(s_Tmax, 1e-4, 1.0)
    Te_max  = (3.0 * (abs(Vth)**2) * (R2 / s_Tmax)) / (w_sync * ((Rth + (R2 / s_Tmax))**2 + (Xth + X2)**2))
    n_Tmax_rpm = (1 - s_Tmax) * ns_rpm
    idx = int(np.argmin(np.abs(Te - T_load)))
    s_oper = float(s[idx])
    n_oper_rpm = float(n_rpm[idx])

    return {
        "s": s, "Te": Te, "n_rpm": n_rpm,
        "Te_start": float(Te_start),
        "s_Tmax": float(s_Tmax),
        "Te_max": float(Te_max),
        "n_Tmax_rpm": float(n_Tmax_rpm),
        "s_oper": float(s_oper),
        "n_oper_rpm": float(n_oper_rpm),
        "ns_rpm": float(ns_rpm),
    }

# Validação rápida
if p <= 0 or f <= 0:
    raise ValueError("Parâmetros inválidos: 'p' e 'f' devem ser positivos.")
for name, val in dict(Rs=Rs, Ls=Ls, Lr=Lr, Lm=Lm, V_ll=V_ll, T_load=T_load).items():
    if val < 0:
        raise ValueError(f"Parâmetro inválido: {name} < 0.")

# ===== Execução =====
results = {}
for Rr in Rr_list:
    if Rr <= 0:
        raise ValueError(f"Rr deve ser positivo. Valor recebido: {Rr}")
    results[Rr] = _torque_curve_regime(
        Rr, p=p, f=f, V_ll=V_ll, conn=conn, Rs=Rs, Ls=Ls, Lr=Lr, Lm=Lm, T_load=T_load
    )

# ===== Tabela =====
rows = []
for Rr, r in results.items():
    rows.append({
        "Rr (Ohm)": Rr,
        "T_partida (N.m)": round(r["Te_start"], 2),
        "s_Tmax (-)": round(r["s_Tmax"], 4),
        "Tmax (N.m)": round(r["Te_max"], 2),
        "n_Tmax (rpm)": round(r["n_Tmax_rpm"], 1),
        f"s_oper (T={T_load:.0f} N.m)": round(r["s_oper"], 4),
        "n_oper (rpm)": round(r["n_oper_rpm"], 1),
    })
df = pd.DataFrame(rows).sort_values("Rr (Ohm)").reset_index(drop=True)

# Exibir na UI
try:
    from google.colab import data_table
    data_table.DataTable(df)     # Colab
except Exception:
    try:
        display(df)              # Jupyter
    except Exception:
        print(df.to_string(index=False))

# CSV opcional
try:
    csv_path = "Q7_resultados_Rr_singlecell.csv"
    df.to_csv(csv_path, index=False)
    print("\nArquivo salvo:", csv_path)
except Exception as e:
    print("Aviso: não foi possível salvar CSV ->", e)

# ===== Gráficos (um por figura) =====
# 1) Torque x Velocidade
plt.figure()
for Rr, r in results.items():
    plt.plot(r["n_rpm"], r["Te"], label=f"Rr={Rr:.2f} Ω")
plt.axhline(T_load, linestyle="--", label="Torque da carga")
plt.xlabel("Velocidade (rpm)")
plt.ylabel("Torque eletromagnético (N·m)")
plt.title("Torque x Velocidade para diferentes Rr")
plt.legend(); plt.grid(True); plt.show()

# 2) Torque de partida vs Rr
plt.figure()
Rr_sorted = sorted(results.keys())
Tstart = [results[Rr]["Te_start"] for Rr in Rr_sorted]
plt.plot(Rr_sorted, Tstart, marker="o")
plt.xlabel("Rr (Ohm)")
plt.ylabel("Torque de partida (N·m)")
plt.title("Variação do torque de partida com Rr")
plt.grid(True); plt.show()

# 3) Escorregamento (regime, T=constante) vs Rr
plt.figure()
s_oper = [results[Rr]["s_oper"] for Rr in Rr_sorted]
plt.plot(Rr_sorted, s_oper, marker="o")
plt.xlabel("Rr (Ohm)")
plt.ylabel("Escorregamento em regime (–)")
plt.title("Escorregamento em regime para T_load fixo")
plt.grid(True); plt.show()

"""# **8. Impacto do Momento de Inércia (J) no Tempo de Aceleração**

***Objetivo: Observar como J influencia a dinâmica de aceleração.***

***Configuração:***

- Modo de Operação: Motor
- J: Variações (ex: 0.04 kg·m², 0.15 kg·m²)
- Torque mecânico final ( Tlfinal): 80.0 Nm

Análise Esperada: Medir o tempo para a máquina atingir a velocidade de regime para diferentes valores de J.
"""

import numpy as np
from scipy.integrate import odeint
import plotly.graph_objects as go
from ipywidgets import FloatSlider, VBox, interactive_output
from IPython.display import display

# Parâmetros do motor e simulação

p = 4                 # Número de polos do motor
f = 60.0              # Frequência da rede (Hz)
wb = 2 * np.pi * f    # Velocidade angular base (rad/s)

Vl = 220.0    # Tensão de linha (V)
Rs = 0.435    # Resistência do estator (Ohm)
Rr = 0.816    # Resistência do rotor (Ohm)
Xm = 26.13    # Reatância magnetizante (Ohm)
Xls = 0.754   # Reatância de dispersão do estator (Ohm)
Xlr = 0.754   # Reatância de dispersão do rotor (Ohm)
B = 0.0       # Coeficiente de atrito viscoso (Nm.s/rad)

# Reatância magnética equivalente (paralelo de Xm, Xls e Xlr)
Xml = 1 / (1/Xm + 1/Xls + 1/Xlr)

# Cálculo da velocidade síncrona (rad/s e rpm)
w_sync = wb * 2 / p
n_sync_rpm = 120 * f / p

# Faixas e valores padrão para sliders interativos
J_min, J_max, J_default = 0.01, 0.4, 0.04      # Momento de inércia (kg·m²)
Tl_min, Tl_max, Tl_default = 0.0, 150.0, 80.0  # Torque mecânico final (Nm)
tempo_subida_t2 = 2.0  # Tempo para o torque aumentar da carga inicial até final (segundos)

# Torque inicial fixo (partida sem carga)
Tl_initial = 0.0

def torque_carga(t, Tl_initial, Tl_final, t2):
    """Torque de carga variando linearmente até t2 segundos."""
    if t < t2:
        return Tl_initial + (Tl_final - Tl_initial) * (t / t2)  # Rampa linear
    else:
        return Tl_final  # Torque constante após t2 segundos

def motor_0dq(states, t, Vqs_t, Vds_t, Tl_inst, w_ref, J):
    # Desempacota variáveis de estado: fluxos e velocidade rotor
    PSIqs, PSIds, PSIqr, PSIdr, wr = states

    # Fluxo magnético no eixo q e d (equivalente magnético)
    PSImq = Xml * (PSIqs / Xls + PSIqr / Xlr)
    PSImd = Xml * (PSIds / Xls + PSIdr / Xlr)

    # Correntes de eixo d e q no estator
    ids = (1 / Xls) * (PSIds - PSImd)
    iqs = (1 / Xls) * (PSIqs - PSImq)

    # Equações diferenciais do fluxo do estator e rotor
    dPSIqs_dt = wb * (Vqs_t - (w_ref / wb) * PSIds + (Rs / Xls) * (PSImq - PSIqs))
    dPSIds_dt = wb * (Vds_t + (w_ref / wb) * PSIqs + (Rs / Xls) * (PSImd - PSIds))
    dPSIqr_dt = wb * (0 - ((w_ref - wr) / wb) * PSIdr + (Rr / Xlr) * (PSImq - PSIqr))
    dPSIdr_dt = wb * (0 + ((w_ref - wr) / wb) * PSIqr + (Rr / Xlr) * (PSImd - PSIdr))

    # Torque eletromagnético instantâneo (Nm)
    Tem = (3 / 2) * (p / 2) * (1 / wb) * (PSIds * iqs - PSIqs * ids)

    # Derivada da velocidade angular do rotor (aceleração)
    dwr_dt = (p / (2 * J)) * (Tem - Tl_inst) - (B / J) * wr

    # Retorna derivadas para o solver ODE
    return [dPSIqs_dt, dPSIds_dt, dPSIqr_dt, dPSIdr_dt, dwr_dt]

def simular_motor(J, Tl_initial, Tl_final, t2, tmax=5.0, h=0.0005):
    """Simula o motor no intervalo de tempo dado, retorna dados para análise."""
    t_values = np.arange(0, tmax, h)  # Vetor de tempos
    states = [0, 0, 0, 0, 0]           # Condições iniciais: fluxos e velocidade zero
    w_ref = wb                       # Velocidade síncrona como referência

    # Listas para armazenar resultados
    wr_res = []
    Te_res = []
    n_res = []

    for t in t_values:
        # Torque mecânico instantâneo na rampa
        Tl_inst = torque_carga(t, Tl_initial, Tl_final, t2)

        # Tensões trifásicas no tempo t (senoidal, base RMS para pico)
        thetae = wb * t
        Va = np.sqrt(2) * Vl * np.sin(thetae)
        Vb = np.sqrt(2) * Vl * np.sin(thetae - 2*np.pi/3)
        Vc = np.sqrt(2) * Vl * np.sin(thetae + 2*np.pi/3)

        # Transformação de Clarke para referência estacionária
        Vaf = np.sqrt(3/2) * (Va - 0.5*Vb - 0.5*Vc)
        Vbt = np.sqrt(3/2) * (0*Va + (np.sqrt(3)/2)*Vb - (np.sqrt(3)/2)*Vc)

        # Transformação Park para referência síncrona dq
        Vds = np.cos(thetae)*Vaf + np.sin(thetae)*Vbt
        Vqs = -np.sin(thetae)*Vaf + np.cos(thetae)*Vbt

        # Integra as equações do motor de t até t+h
        sol = odeint(motor_0dq, states, [t, t+h], args=(Vqs, Vds, Tl_inst, w_ref, J))
        states = sol[1]  # Atualiza estados para próxima iteração
        PSIqs, PSIds, PSIqr, PSIdr, wr = states

        # Armazena velocidade em rpm
        wr_res.append(wr)
        n = (120 / p) * (wr / (2 * np.pi))
        n_res.append(n)

        # Calcula torque eletromagnético para análise
        PSImq = Xml * (PSIqs / Xls + PSIqr / Xlr)
        PSImd = Xml * (PSIds / Xls + PSIdr / Xlr)
        ids = (1 / Xls) * (PSIds - PSImd)
        iqs = (1 / Xls) * (PSIqs - PSImq)
        Te = (3 / 2) * (p / 2) * (1 / wb) * (PSIds * iqs - PSIqs * ids)
        Te_res.append(Te)

    # Converte resultados para arrays NumPy
    wr_res = np.array(wr_res)
    n_res = np.array(n_res)
    Te_res = np.array(Te_res)
    t_values = np.array(t_values)

    # Calcula o tempo que o motor leva para atingir 95% da velocidade síncrona
    n_target = 0.95 * n_sync_rpm
    t95 = np.nan  # Caso não alcance
    idxs = np.where(n_res >= n_target)[0]
    if len(idxs) > 0:
        t95 = t_values[idxs[0]]

    return t_values, n_res, Te_res, t95

from google.colab import output
output.enable_custom_widget_manager()  # Ativa suporte a widgets no Colab

def atualizar_grafico(J_value, Tl_final_value):
    # Executa a simulação para os parâmetros atuais dos sliders
    t_values, n_res, Te_res, t95 = simular_motor(J_value, Tl_initial, Tl_final_value, tempo_subida_t2)

    # Cria figura com Plotly
    fig = go.Figure()
    # Adiciona curva da velocidade em rpm
    fig.add_trace(go.Scatter(x=t_values, y=n_res, mode='lines', name='Velocidade (RPM)',
                             line=dict(color='royalblue', width=3)))
    # Adiciona curva do torque eletromagnético
    fig.add_trace(go.Scatter(x=t_values, y=Te_res, mode='lines', name='Torque Eletromagnético (Nm)',
                             line=dict(color='firebrick', width=3, dash='dash')))

    # Linha horizontal marcando 95% da velocidade síncrona
    fig.add_shape(type="line", x0=t_values[0], y0=0.95 * n_sync_rpm,
                  x1=t_values[-1], y1=0.95 * n_sync_rpm,
                  line=dict(color="green", width=2, dash="dot"))
    # Anotação explicativa da linha de referência
    fig.add_annotation(x=t_values[int(len(t_values)*0.6)], y=0.95 * n_sync_rpm,
                       text="95% Vel. Síncrona", showarrow=False,
                       font=dict(color="green", size=12), bgcolor="white", opacity=0.8)

    # Configura layout do gráfico
    fig.update_layout(
        title=f"Simulação Motor Indução - J={J_value:.3f} kg·m², Torque Final={Tl_final_value:.1f} Nm",
        xaxis_title="Tempo (s)",
        yaxis_title="Velocidade (RPM) / Torque (Nm)",
        hovermode="x unified",
        legend=dict(x=0.01, y=0.99, bgcolor='rgba(255,255,255,0.8)', bordercolor='black', borderwidth=1),
        template="plotly_white",
        margin=dict(l=50, r=50, t=80, b=50)
    )
    # Exibe gráfico
    fig.show()

    # Imprime tempo para atingir 95% da velocidade síncrona
    print(f"Tempo para atingir 95% da velocidade síncrona: {t95:.3f} s")

# Configuração dos sliders para parâmetros interativos
slider_J = FloatSlider(value=J_default, min=J_min, max=J_max, step=0.005,
                       description='Momento de Inércia J (kg·m²)', continuous_update=False)
slider_Tl = FloatSlider(value=Tl_default, min=Tl_min, max=80.0, step=1.0,
                       description='Torque final (Nm)', continuous_update=False)

# Liga sliders à função que atualiza o gráfico
out = interactive_output(atualizar_grafico, {'J_value': slider_J, 'Tl_final_value': slider_Tl})

# Exibe sliders e gráfico na vertical
display(VBox([slider_J, slider_Tl, out]))

"""Percebe-se que a alteração do valor de J influencia no tempo em que a máquina leva para chegar a velocidade síncrona. Valore menores permitem uma aceleração maior mas deixam o sistema mais oscilante. Valores maiores diminuem a aceleração mas fazem com que o motor tenha uma caracterítica mais estável.

#9. Variação da Frequência da Rede
* Objetivo: Analisar o impacto da frequência nominal no comportamento do motor.

Configuração:

* Modo de Operação: Motor
* Frequência (f): Variações (ex: 50.0 Hz, 40.0 Hz)
* Tensão RMS de entrada ( Vl): 220.0 V (ou ajustar para V/f constante, ex: 183V para 50Hz)
* Torque mecânico final ( Tlfinal ): 80.0 Nm

Análise Esperada: Observar a velocidade síncrona, a velocidade de regime e o escorregamento.
"""

# Questão 9 - Simulação da variação da frequência da rede em motor de indução trifásico

import numpy as np
import matplotlib.pyplot as plt

# -------------------------
# Dados do motor (valores típicos de catálogo)
# -------------------------
R1 = 0.641      # Resistência do estator [ohm]
R2 = 0.332      # Resistência do rotor referida ao estator [ohm]
X1 = 1.106      # Reatância do estator [ohm]
X2 = 0.464      # Reatância do rotor referida ao estator [ohm]
Xm = 26.3       # Reatância de magnetização [ohm]
polos = 4       # Número de polos
T_mec = 80      # Torque mecânico aplicado [Nm]
V_nom = 220     # Tensão nominal RMS fase-fase [V]
f_nom = 50      # Frequência nominal [Hz]

# Frequências de teste
frequencias = [50, 40]

# Função para calcular torque em função do escorregamento
def torque_motor(V, f, s):
    ws = 2 * np.pi * f / (polos/2)  # Velocidade síncrona elétrica [rad/s]
    Z1 = R1 + 1j*X1
    Zm = 1j*Xm
    Z2 = R2/s + 1j*X2
    Z_th = Z1 + (Zm*Z2)/(Zm+Z2)
    I2 = V / Z_th
    P_conv = 3 * (abs(I2)**2) * (R2/s) * (1-s)  # Potência convertida mecânica [W]
    Te = P_conv / (ws*(1-s))
    return Te

# Loop para simular e exibir resultados
for f in frequencias:
    print(f"\n=== Resultados para f = {f} Hz ===")
    V = V_nom * (f / f_nom)  # Ajuste de tensão para manter V/f constante
    ns = 120 * f / polos     # Velocidade síncrona [rpm]

    s_vals = np.linspace(0.001, 0.1, 200)
    T_vals = [torque_motor(V, f, s) for s in s_vals]

    # Encontrar velocidade de regime (torque = T_mec)
    idx_regime = np.argmin(np.abs(np.array(T_vals) - T_mec))
    s_regime = s_vals[idx_regime]
    n_regime = ns * (1 - s_regime)
    ws_regime = 2 * np.pi * n_regime / 60

    # Corrente no regime
    Z1 = R1 + 1j*X1
    Zm = 1j*Xm
    Z2 = R2/s_regime + 1j*X2
    Z_th = Z1 + (Zm*Z2)/(Zm+Z2)
    I_regime = V / Z_th

    # Potência mecânica e eficiência
    P_mec = (2*np.pi*n_regime/60) * T_mec
    P_entrada = 3 * abs(I_regime)**2 * R1 + P_mec/(1 - s_regime)
    eficiencia = P_mec / P_entrada * 100

    # Resultados numéricos
    print(f"Velocidade síncrona: {ns:.2f} rpm")
    print(f"Velocidade de regime: {n_regime:.2f} rpm")
    print(f"Escorregamento: {s_regime*100:.2f} %")
    print(f"Corrente de regime: {abs(I_regime):.2f} A")
    print(f"Potência mecânica: {P_mec:.2f} W")
    print(f"Eficiência: {eficiencia:.2f} %")

    # Gráfico Torque x Velocidade
    n_vals = ns * (1 - s_vals)
    plt.plot(n_vals, T_vals, label=f"{f} Hz")

plt.axhline(T_mec, color='k', linestyle='--', label='Torque Mecânico')
plt.xlabel("Velocidade (rpm)")
plt.ylabel("Torque Eletromagnético (Nm)")
plt.title("Torque x Velocidade para diferentes frequências")
plt.legend()
plt.grid(True)
plt.show()

# ===============================
# Escorregamento x Torque com pontos de regime
# ===============================
plt.figure(figsize=(8,6))

for f in frequencias:
    V = V_nom * (f / f_nom)
    s_vals = np.linspace(0.001, 1.0, 300)  # até 100% de escorregamento
    T_vals = [torque_motor(V, f, s) for s in s_vals]

    plt.plot(T_vals, s_vals*100, label=f"{f} Hz")

    # Calcular ponto de regime
    idx_regime = np.argmin(np.abs(np.array(T_vals) - T_mec))
    plt.plot(T_vals[idx_regime], s_vals[idx_regime]*100, 'o', label=f"Regime {f} Hz")

    # Anotar valor numérico
    plt.text(T_vals[idx_regime], s_vals[idx_regime]*100 + 1,
             f"{s_vals[idx_regime]*100:.2f}%", ha='center')

plt.xlabel("Torque eletromagnético (Nm)")
plt.ylabel("Escorregamento (%)")
plt.title("Escorregamento x Torque para diferentes frequências")
plt.grid(True)
plt.legend()
plt.show()

print("""
Análise:
- A 50 Hz, o motor apresenta velocidade síncrona de 1500 rpm e de regime ~1457 rpm (escorregamento ≈ 2,84%).
- A 40 Hz, a velocidade síncrona reduz para 1200 rpm e o regime ~1151 rpm (escorregamento ≈ 4,08%).
- A redução de frequência aumenta o escorregamento necessário para gerar o mesmo torque.
""")